---

# Configure debian package
- name: "Package debconf postfix package configuration"
  debconf:
    name: postfix
    question: "{{ item['question'] }}"
    value: "{{ item['value'] }}"
    vtype: "{{ item['vtype'] }}"
  become: true
  changed_when: false
  no_log: true
  tags: debconf
  loop:
    - question: postfix/main_mailer_type
      value: "{{ postfix_main_mailer_type }}"
      vtype: select

    - question: postfix/mailname
      value: "{{ postfix_mailname }}"
      vtype: string

    - question: postfix/destinations
      value: "{{ postfix_destinations }}"
      vtype: string

    - question: postfix/root_address
      value: "{{ postfix_root_address }}"
      vtype: string

    - question: postfix/mynetworks
      value: "{{ postfix_mynetworks }}"
      vtype: string

    - question: postfix/protocols
      value: "{{ postfix_inet_protocols }}"
      vtype: select

    - question: postfix/chattr
      value: "{{ postfix_chattr }}"
      vtype: string

    - question: postfix/recipient_delim
      value: "{{ postfix_recipient_delim }}"
      vtype: string

    - question: postfix/mailbox_limit
      value: "{{ postfix_destinations }}"
      vtype: string

    - question: postfix/relayhost
      value: "{{ postfix_relayhost }}"
      vtype: string
      
      

# Install the packages
- name: "Install packages"
  apt:
    name: "{{ postfix_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  tags: package
