---
- name: "Syncprel Provider: create /etc/ldap/ldif-templates/syncprov.ldif"
  copy:
    dest: "/etc/ldap/ldif-templates/syncprov.ldif"
    content: |
      dn: cn=module{0},cn=config
      changetype: modify
      add: olcModuleLoad
      olcModuleLoad: syncprov
  register: syncprov_ldif

- name: "Syncprel Provider: apply /etc/ldap/ldif-templates/syncprov.ldif"
  shell: "ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/ldap/ldif-templates/syncprov.ldif"
  ignore_errors: true
  when: syncprov_ldif.changed
