---

dev:
  children:
    ldap:
    openvpn:
    mail:
    postgresql:

ldap:
  children:
    ldap_producers:
    ldap_consumers:

ldap_producers:
  hosts:
    ldap-01.dev.qimata

ldap_consumers:
  hosts:
    ldap-02.dev.qimata

openvpn:
  hosts:
    openvpn-01.dev.qimata

mail:
  hosts:
    smtp-01.dev.qimata

postgresql:
  children:
    psql_pgpool:
    psql_01:
    psql_02:
    psql_whitness:

psql_01:
  hosts:
    db-01.dev.qimata

psql_02:
  hosts:
    db-02.dev.qimata

psql_pgpool:
  hosts:
    db-03.dev.qimata

psql_whitness:
  hosts:
    db-04.dev.qimata
