---

dev:
  children:
    ldap:
    openvpn:
    smtp:

ldap:
  children:
    ldap_producers:
    ldap_consumers:

ldap_producers:
  hosts:
    ldap-01.dev.qimata
ldap_consumers:
  hosts:
    ldap-02.dev.qimata
openvpn:
  hosts:
    openvpn-01.dev.qimata
smtp:
  hosts:
    smtp-01.dev.qimata
