---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 600
  changed_when: false
  failed_when: false
  when: ansible_os_family == 'Debian'

- name: Install Dependencies
  apt:
    pkg: 
    - curl
    - initscripts
    - libcurl4
    - unzip
    state: latest
    update_cache: yes