- hosts: all
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  # All hosts get the UFW role
  - role: ufw
    tags:
    - ufw

- hosts: ldap
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: openldap
    tags:
    - openldap

- hosts: openvpn
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: openvpn
    tags:
    - openvpn

- hosts: bind_master
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: systemli.bind9
    tags:
    - bind
    - bind_master

- hosts: bind_slave
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: systemli.bind9
    tags:
    - bind
    - bind_slave

  

- hosts: ca
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: ca
    tags:
    - ca