- hosts: all
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  # Setup what we need to run ansible on host
  - role: ansible
    tags:
      ansible
  # All hosts get the UFW role
  - role: ufw
    tags:
    - ufw

- hosts: ldap
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: openldap
    tags:
    - openldap

- hosts: openvpn
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: openvpn
    tags:
    - openvpn

- hosts: mail
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: postfix
    tags:
    - postfix
  - role: dovecot
    tags:
    - dovecot
  - role: roundcube
    tags:
    - roundcube

- hosts: psql_pgpool
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: pgpool
    tags:
    - pgpool

- hosts: psql_01
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: postgresql
    tags:
    - postgresql
    - postgresql_main

- hosts: psql_02
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: postgresql
    tags:
    - postgresql
    - postgresql_replica

- hosts: psql_whitness
  become: yes
  gather_facts: yes
  gather_timeout: 120

  roles:
  - role: postgresql
    tags:
    - postgresql
