---

- name: "Config postgresql.conf"
  template:
    src: "postgresql-13.conf.j2"
    dest: "{{postgresql_config_file}}"
    owner: "{{postgresql_user}}"
    group: "{{postgresql_group}}"
    mode: 0644
  become: true
  # notify: restart postgresql
  register: config_postgresql_conf_result
  tags: config

- name: "Config postgresql.conf"
  service:
    name: postgresql
    state: restarted
  when: config_postgresql_conf_result.changed
  tags: config

- name: "Config pg_hba.conf"
  template:
    src: "pg_hba.conf.j2"
    dest: "{{postgresql_hba_file}}"
    owner: "{{postgresql_user}}"
    group: "{{postgresql_group}}"
    mode: 0644
  become: true
  # notify: restart postgresql
  register: config_pg_hba_conf_result
  tags: config


- name: "Config pg_hba.conf"
  service:
    name: postgresql
    state: restarted
  when: config_pg_hba_conf_result.changed
  tags: config

- name: "Add admin user"
  become: true
  become_user: "{{postgresql_user}}"
  community.postgresql.postgresql_user:
    name: "{{postgresql_admin_user_name}}"
    password: "{{postgresql_admin_user_password}}"
    comment: "Admin user"
    login_unix_socket: "{{postgresql_unix_socket_directory}}"
    port: "{{postgresql_port}}"
    role_attr_flags: "{{postgresql_admin_user_attr_flags}}"
    state: "{{postgresql_admin_user_state}}"
  tags: admin_user
  when: (postgresql_replication_role == "primary") or
        (postgresql_replication_role == "")

