---

# Install the packages
- name: "Package: install packages"
  apt:
    name: "{{ postgresql_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  tags: package
