---

- name: Create client config directory
  file:
    state: directory
    path: "{{ openvpn_server_dir }}"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: 0750

- name: Create openvpn server config file
  template:
    src: server.conf.j2
    dest: "{{ openvpn_server_dir }}/openvpn.conf"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: "0644"
  notify:
    - restart openvpn-server

- name: Copy up script if defined
  copy:
    src: "{{ openvpn_script_up }}"
    dest: "{{ openvpn_base_dir }}/up.sh"
    mode: a+x
  when: openvpn_script_up is defined

- name: Copy down script if defined
  copy:
    src: "{{ openvpn_script_down }}"
    dest: "{{ openvpn_base_dir }}/down.sh"
    mode: a+x
  when: openvpn_script_down is defined

- name: Copy client-connect script if defined
  copy:
    src: "{{ openvpn_script_client_connect }}"
    dest: "{{ openvpn_base_dir }}/client_connect.sh"
    mode: a+x
  when: openvpn_script_client_connect is defined

- name: Copy client-disconnect script if defined
  copy:
    src: "{{ openvpn_script_client_disconnect }}"
    dest: "{{ openvpn_base_dir }}/client_disconnect.sh"
    mode: a+x
  when: openvpn_script_client_disconnect is defined

- name: Copy openvpn logrotate config file
  template:
    src: openvpn_logrotate.conf.j2
    dest: /etc/logrotate.d/openvpn-{{ openvpn_config_file }}.conf
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: 0400
