# Install the packages
- name: "Install packages"
  apt:
    name: "{{ openvpn_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  tags: openvpn, package


- name: "Install plugin packages"
  apt:
    name: "{{ openvpn_packages_plugin_ldap }}"
    state: present
  become: true
  register: result
  until: result is successful
  tags: openvpn, package
  when: openvpn_use_ldap | bool
